### ISSUE TITLE
npm install --dev fails

### ISSUE THREAD

**Issue by anthonygreen** [jbpros/cukecipes#6]
```
npm install --dev 
```

fails with the error

```
npm ERR! Error: EMFILE, too many open files
npm ERR!     at new Glob (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/glob/glob.js:105:21)
npm ERR!     at glob (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/glob/glob.js:57:11)
npm ERR!     at wscript (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/read-package-json/read-json.js:150:17)
npm ERR!     at /usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:40
npm ERR!     at /usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/slide/lib/async-map.js:53:8)
npm ERR!     at extras (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 10.8.0
npm ERR! command "/usr/local/Cellar/node/0.8.14/bin/node" "/usr/local/bin/npm" "install" "--dev"
```

After reinstalling node 

```
 npm install -dev
```

continues to fail only this time it goes into a recursive loop and never exits

```
npm ERR! Error: ENOENT, lstat '/Users/greena28/Projects/cukecipes/node_modules/cukestall/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/difflet/node_modules/traverse/node_modules/tap/lib/main.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! cwd /Users/greena28/Projects/cukecipes
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! path /Users/greena28/Projects/cukecipes/node_modules/cukestall/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/difflet/node_modules/traverse/node_modules/tap/lib/main.js
npm ERR! fstream_path /Users/greena28/Projects/cukecipes/node_modules/cukestall/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/difflet/node_modules/traverse/node_modules/tap/lib/main.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack Writer._finish.er.fstream_finish_call (/usr/local/Cellar/node/0.8.16/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm http GET https://registry.npmjs.org/jison/-/jison-0.2.11.tgz
npm ERR! Error: ENOENT, open '/Users/greena28/Projects/cukecipes/node_modules/cucumber/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/tap/coverage-example/test/baz.test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! cwd /Users/greena28/Projects/cukecipes
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! path /Users/greena28/Projects/cukecipes/node_modules/cucumber/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/tap/coverage-example/test/baz.test.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, open '/Users/greena28/Projects/cukecipes/node_modules/cukestall/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/tap/coverage-example/test/baz.test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "--dev"
npm ERR! cwd /Users/greena28/Projects/cukecipes
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! path /Users/greena28/Projects/cukecipes/node_modules/cukestall/node_modules/browserify/node_modules/backbone/node_modules/phantomjs/node_modules/unzip/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/tap/coverage-example/test/baz.test.js
npm ERR! code ENOENT
npm ERR! errno 34
[....]
```

**Comment by anthonygreen** [comment]
```
npm install
```

has no issues

**Comment by jbpros** [comment]
Thanks for reporting it, it's a _known_ (by me anyway) issue.

**Comment by rhiadj** [comment]
I'm also experiencing this same issue (on main dev machine - Mac OS X 10.7 and on another machine - Mac OS X 10.6). 

Was wondering if you'd seen either of these suggested fixes:
http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files
http://stackoverflow.com/questions/8850605/fs-writefile-hangs-on-high-load-no-error-on-v-0-6-6/8854173#8854173

Many thanks.

**Comment by Sivli-Embir** [comment]
+1 on Mac OS X 10.8.2.

**Comment by danieljsun** [comment]
I encountered similar problem as reported by @anthonygreen 
increase the file descriptor limit solved it

``` sh
ulimit -n 8192
```
