### ISSUE TITLE
node server.js fails

### ISSUE THREAD

**Issue by anthonygreen** [jbpros/cukecipes#7]
after installing with

```
npm install
```

then

```
node server.js
```

fails

```
Listening on port 9797

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: failed to connect to [localhost:27017]
    at Server.connect.connectionPool.on.server._serverState (/Users/greena28/Projects/cukecipes/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:477:73)
    at EventEmitter.emit (events.js:126:20)
    at connection.on._self._poolState (/Users/greena28/Projects/cukecipes/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:92:15)
    at EventEmitter.emit (events.js:99:17)
    at Socket.errorHandler (/Users/greena28/Projects/cukecipes/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:387:10)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by anthonygreen** [comment]
Requires you to start mongoDB before running 

```
 node server.js
```

**Comment by jarl-dk** [comment]
Thanks...
And on Ubuntu that means

```
sudo service mongodb start
```

Maybe preceded by a 

```
sudo service mongodb stop
```
